import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/layout/navbar";
import ReactQueryProvider from "@/providers/react-query.provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body>
				<ReactQueryProvider>
					<Toaster />
					<Navbar />
					{children}
				</ReactQueryProvider>
			</body>
			{/* // Todo: footer */}
		</html>
	);
}
